### ISSUE TITLE
您好，我在使用actions运行时遇到了一点问题

### ISSUE THREAD

**Issue by Royfor12** [NianBroken/ZFCheckScores#10]
貌似是教务处的网络原因，教务处网址已发送至您邮箱
<img width="504" alt="image" src="https://github.com/NianBroken/ZFCheckScores/assets/38993737/f553d2bd-a42b-4952-9c03-f384bce57f2c">

**Comment by Royfor12** [comment]
我看了一下之前的issue，发现标准格式为https://jw.******.cn/jwglxt/xtgl，而我的教务系统使用的是
https://jwxt.********.edu.cn/jwglxt/xtgl/login_slogin.html，指向了一个html页面，是否是这样原因导致无法使用该项目？

**Comment by NianBroken** [comment]
您的教务系统网址通过requests库进行访问时，返回的状态码为202，而非200。
但其他网址以及其他教务系统网址返回的状态码均是200。
经多次尝试，目前暂未找到对该问题的解决方法，您可能需要等待一段时间，该问题才会被解决。

**Comment by Royfor12** [comment]
感谢您的付出🥹🥹🥹

**Comment by NianBroken** [comment]
> 感谢您的付出🥹🥹🥹

问题未解决，无需关闭issues

**Comment by NianBroken** [comment]
经多次尝试，由于技术不足，无法解决该问题。

你的教务系统在第一次被访问时，会返回202错误，并返回**第一个**cookie，`ZXniXLfxkjSbO`的值。
例如：

```
HTTP/1.1 202 Accepted
Set-Cookie: ZXniXLfxkjSbO=60cZApKWja0.9PsaQpLbCQ8EeDuS3Ov8WJj4vK11vw8SRkYSRnerMZz72Sd8UHl2wWCZdbErcNk7_85HAjSgL95q;
```

之后浏览器会访问一个名为`S4alvlTfyGjj.dda4d0f.js`的js文件，通过**第一个**cookie，计算得出**第二个**cookie，`ZXniXLfxkjSbP`的值。
例如：

```
ZXniXLfxkjSbP=0PXfkfOe_gik8RyhUszDUUe5yIbXFMikoLbAO9QYrG92dEBxaUgLu0dpTWugzKvjBKz0y6.aHhEPalGh13cpZlrISHzIopzIgGgg43CKA.HxLY.LEXwj3DOUwyDQltOYy3y73BGbUZwxmQAO0vpcaV8zSVI._AUmiUxivjzROVnJ7JDxjSkgtf1RQCnQJfL71W7AxNsofTiIKS2_Zt50M1vMuKxuFdZw8cvqQqFyPBLcHfl4X87yE08JOjOi9WldWhyWiTzYmSE8eZSwavAiyfG
```

最后，需同时附带以上两个cookie进行第二次访问你的教务系统，才能被正常访问。
例如：

```
ZXniXLfxkjSbO=60cZApKWja0.9PsaQpLbCQ8EeDuS3Ov8WJj4vK11vw8SRkYSRnerMZz72Sd8UHl2wWCZdbErcNk7_85HAjSgL95q; 
ZXniXLfxkjSbP=0PXfkfOe_gik8RyhUszDUUe5yIbXFMikoLbAO9QYrG92dEBxaUgLu0dpTWugzKvjBKz0y6.aHhEPalGh13cpZlrISHzIopzIgGgg43CKA.HxLY.LEXwj3DOUwyDQltOYy3y73BGbUZwxmQAO0vpcaV8zSVI._AUmiUxivjzROVnJ7JDxjSkgtf1RQCnQJfL71W7AxNsofTiIKS2_Zt50M1vMuKxuFdZw8cvqQqFyPBLcHfl4X87yE08JOjOi9WldWhyWiTzYmSE8eZSwavAiyfG
```

```
HTTP/1.1 200 OK
```

附`js`文件
[S4alvlTfyGjj.dda4d0f.js.zip](https://github.com/NianBroken/ZFCheckScores/files/15499168/S4alvlTfyGjj.dda4d0f.js.zip)
