### ISSUE TITLE
运行推送问题

### ISSUE THREAD

**Issue by xM3GAN** [NianBroken/ZFCheckScores#13]
程序action第一次运行成功，push收到了推送信息，但是第二次运行仍然收到了推送，未开启true强制推送，且每一次action都是程序运行成功的页面，如下
![image](https://github.com/NianBroken/ZFCheckScores/assets/80143495/958d05eb-30ec-4d72-9d4f-7876fa654080)
![image](https://github.com/NianBroken/ZFCheckScores/assets/80143495/680cb2b7-5352-4829-95f9-23bcdc41c9f0)

没有像大佬的一样显示成绩是否更新
![image](https://github.com/NianBroken/ZFCheckScores/assets/80143495/8e5aad8e-31ca-4320-8f5d-b2240f47ea18)

**Comment by NianBroken** [comment]
已修复，你同步一下上游分支，再运行一遍看下问题是否已被修复。

**Comment by xM3GAN** [comment]
同步分支再次运行已无问题
![image](https://github.com/NianBroken/ZFCheckScores/assets/80143495/b8ccb3c1-e2eb-4fe1-9bb7-b2b80f75a91c)
