### ISSUE TITLE
报错1002，用户名或密码不正确

### ISSUE THREAD

**Issue by yizhi02** [NianBroken/ZFCheckScores#14]
![CleanShot 2024-06-25 at 11 35 15@2x](https://github.com/NianBroken/ZFCheckScores/assets/150669444/d7adf32c-eee8-4079-8679-244d1cee5092)
检查了几次secrets，应该不是输错了用户名或者密码
教务网址似乎只有http能够访问：http://xuanke.cufe.edu.cn/jwglxt/xtgl

感谢大佬

**Comment by yizhi02** [comment]
![CleanShot 2024-06-25 at 11 39 31@2x](https://github.com/NianBroken/ZFCheckScores/assets/150669444/6b094f59-94ff-44e6-838a-5e92ea468781)
如果用这个网址的话，会变成上面的报错：http://xuanke.cufe.edu.cn/jwglxt

**Comment by NianBroken** [comment]
suinian666@gmail.com

向该邮箱发送教务系统账号密码，我帮你排查一下问题。

**Comment by NianBroken** [comment]
问题已解决，你同步一下上游分支，再次尝试一下。
