### ISSUE TITLE
只能用校园内网登录的教务系统是不是用不了

### ISSUE THREAD

**Issue by w937521t** [NianBroken/ZFCheckScores#15]
校园外网登录要微信扫码验证或者手机号验证，所以我在URL里填的内网，但我们学校的教务系统十一点后关闭，我看actions也正常。很奇怪
![QQ截图20240704083326](https://github.com/NianBroken/ZFCheckScores/assets/159742485/a9e64392-7fdf-48a3-baa6-8a3391162e28)

**Comment by NianBroken** [comment]
要点进去看里面main.py的运行结果。
工作流正常只是代表代码没有报错，而不是代表程序正常运行。

**Comment by w937521t** [comment]
![image](https://github.com/NianBroken/ZFCheckScores/assets/159742485/f30b07d9-505e-417a-8174-b27fb184488b)
看样子是用不了 外网登录需要微信验证

**Comment by NianBroken** [comment]
你可以在学校搭一个中转的机子，用外网访问中转，中转访问教务系统。
