### ISSUE TITLE
报错，按步骤来的操作，然后在github 的actions他那边也是提示运行成果，但是运行我去看结果只会显示如图

### ISSUE THREAD

**Issue by zwqqq1** [NianBroken/ZFCheckScores#16]
![73d181cb3603d29357f8650e6511c82](https://github.com/NianBroken/ZFCheckScores/assets/174992471/8afcc0c3-3033-44f8-8e93-9d46844620ab)

**Comment by zwqqq1** [comment]
有检查过几遍和重新弄了几遍，同样是提示如图，教务系统的账号密码网址都没有问题：就是一直提示如下：{'code': 2333, 'msg': '教务系统挂了'}
------
Force Push Message: False
Triggered By: schedule

**Comment by Linw0** [comment]
一样的问题

**Comment by NianBroken** [comment]
该错误是由于教务系统登录时需填写验证码所导致的，目前该项目无法绕过验证码或自动识别验证码。
在[ae03af5](https://github.com/NianBroken/ZFCheckScores/commit/ae03af5a50830f740c97d34c03e9f0a4ce884eec)次更新中，我对检测到验证码的情况做出了正确的提示。

<img width="258" src="https://github.com/user-attachments/assets/1c062f33-5980-4033-b470-a87d8f045b94">
<img width="258" src="https://github.com/user-attachments/assets/2948a4a4-7f32-4e7d-adda-20c824e66e7a">

**Comment by FarmerChillax** [comment]
自动处理验证码：https://github.com/FarmerChillax/new-school-sdk

**Comment by zwqqq1** [comment]
很久没有使用了，想问一下有让微信自动提醒的教程吗



















在 2024-10-21 16:38:59，"Farmer.Chillax" ***@***.***> 写道：

自动处理验证码：https://github.com/FarmerChillax/new-school-sdk

**Comment by FarmerChillax** [comment]
这个 repo 只是做了「正方教务系统」接口的封装，并没有其余增强能力提供，目前也没有精力做相关增强功能了。

只是路过看到这个仓库在这方面能力的缺失提一嘴，看看有没有人愿意对接这个 sdk 做开发吧，欢迎 PR。

**Comment by NianBroken** [comment]
@zwqqq1 ,
[本项目](https://github.com/NianBroken/ZFCheckScores)支持微信自动提醒，你可以将[new-school-sdk](https://github.com/FarmerChillax/new-school-sdk)中的自动处理验证码的相关的代码移植到本项目中使用。
