### ISSUE TITLE
BUG：教务系统挂了

### ISSUE THREAD

**Issue by wangzhenxing4** [NianBroken/ZFCheckScores#17]
我认真的多次检查了秘密，并使用多个网站，例如：http://jwgl.sxzy.edu.cn，http://jwgl.sxzy.edu.cn/default2.aspx，如果是https则无法访问，但是，我的URL是http，我需要您的帮助
<img width="1440" alt="截屏2024-07-15 11 01 59" src="https://github.com/user-attachments/assets/ee0aa74a-af3c-4962-8ab1-9229c3d8cc60">

**Comment by NianBroken** [comment]
suinian666@gmail.com
向此邮箱发送教务系统账号密码，我才能定位问题。

**Comment by wangzhenxing4** [comment]
我现在已向该邮箱发送教务系统账户和密码，非常感谢您的回复，希望能得到您的帮助

碎念_Nian ***@***.***> 于2024年7月15日周一 15:29写道：

**Comment by NianBroken** [comment]
你的教务系统版本太旧，因此无法使用本项目。

**Comment by wangzhenxing4** [comment]
> 你的教务系统版本太旧，因此无法使用本项目。

好的吧，那没办法了，还是麻烦您了，谢谢
