### ISSUE TITLE
成绩推送失败

### ISSUE THREAD

**Issue by 3228222175** [NianBroken/ZFCheckScores#23]
<img width="731" alt="微信图片_20240828163201" src="https://github.com/user-attachments/assets/e61c0b95-933c-452a-80bb-7e12f99f9c81">

**Comment by NianBroken** [comment]
@3228222175 你的教务系统的Url填写错了，程序会自动在末尾加上"`xtgl/login_slogin.html`"。

因此你无需在环境变量中填写"`xtgl/login_slogin.html`"

下图为你填写的环境变量，可以看到它出现了两个"`xtgl/login_slogin.html`"

![Screenshot_2024-08-28-16-35-16-029_mark via](https://github.com/user-attachments/assets/dcc0b9a6-3bbc-49f0-ad68-f6ae5988cc54)

**Comment by 3228222175** [comment]
已解决 感谢哥
