### ISSUE TITLE
教务系统只能用统一身份认证平台登陆怎么办

### ISSUE THREAD

**Issue by miloce** [NianBroken/ZFCheckScores#25]
学校只给用统一身份认证平台登陆是不是不能用

**Comment by NianBroken** [comment]
是的

**Comment by Vdk1639** [comment]
我们学校也是必须用统一身份认证平台登陆，我自己fork的方式是用selenium先登录进去跳转教务，然后传出session对接原项目

**Comment by NianBroken** [comment]
@Vdk1639 可以提一个PR

**Comment by Vdk1639** [comment]
> @Vdk1639 可以提一个PR

我这边只适配了我们学校的CAS，而且自己觉得有些地方还不够优雅，我等优化一下会提交，只是觉得仅适配了我们学校采用的CAS受众有限😂

**Comment by Vdk1639** [comment]
> selenium理论上可以适配所有学校吧
> 
> 只要能够定位到账号输入框和密码输入框，以及登录按钮即可。

是的，我的定位逻辑只能保证我们学校的，考虑的其他学校的CAS系统可能与我们的不同，我觉得单独提一个请求意义不大
