### ISSUE TITLE
报错信息为1003, 登录超时

### ISSUE THREAD

**Issue by Irregular2333** [NianBroken/ZFCheckScores#5]
都按Markdown里面的步骤来的，最后actions里面跑的时候每次都是{'code': 1003, 'msg': '登录超时'}，token和教务系统网站以及账号密码那些应该都对的，不知道哪里出问题了
~~总不可能是因为验证码的问题？~~

**Comment by Irregular2333** [comment]
> 提供一下教务系统url，我看下是否是版本不支持 [suinian666@gmail.com](mailto:suinian666@gmail.com)

https://jwweb.scujcc.cn/

**Comment by NianBroken** [comment]
你的教务系统版本太老了

**Comment by NianBroken** [comment]
> 你的教务系统版本太老了

你的教务系统版本太老了

**Comment by NianBroken** [comment]
> > 提供一下教务系统url，我看下是否是版本不支持 [suinian666@gmail.com](mailto:suinian666@gmail.com)
> 
> https://jwweb.scujcc.cn/

你的教务系统版本太老了

**Comment by Irregular2333** [comment]
> > > 提供一下教务系统url，我看下是否是版本不支持 [suinian666@gmail.com](mailto:suinian666@gmail.com)
> > 
> > 
> > https://jwweb.scujcc.cn/
> 
> 你的教务系统版本太老了

好吧，不过还是谢谢了😂
