### ISSUE TITLE
能不能弄一个课程推送的牛逼大哥

### ISSUE THREAD

**Issue by StarSink9** [NianBroken/ZFCheckScores#7]

**Comment by NianBroken** [comment]
每日推送当日课程吗？还是检测课程是否更新？

**Comment by StarSink9** [comment]
对的大佬，就是每天在上课之前提醒一下课程，但是我觉得光靠github好像不太行

**Comment by NianBroken** [comment]
理论是可行的

**Comment by StarSink9** [comment]
我按照教程设置的是正确的
但是我并没有收到推送信息

**Comment by StarSink9** [comment]
![image](https://github.com/NianBroken/ZFCheckScores/assets/112603695/2dade1e0-4527-46ef-8d6d-4d147497990c)
错误原因

**Comment by StarSink9** [comment]
> [suinian666@gmail.com](mailto:suinian666@gmail.com) 私发我一下你的教务系统网址

已经发给你了，谢谢啦

**Comment by NianBroken** [comment]
> > [suinian666@gmail.com](mailto:suinian666@gmail.com) 私发我一下你的教务系统网址
> 
> 已经发给你了，谢谢啦

经测试，你的教务系统可以完美使用本项目，日志中的错误信息是由于你没有正确填写教务系统的URL所导致的。
你的教务系统URL应该填写为：“`https://jw.******.cn/jwglxt/xtgl`”（敏感部分以打码）。
下列为部分错误示范：
`jw.******.cn`
`https://jw.******.cn/`
`https://jw.******.cn/jwglxt/`
`https://jw.******.cn/jwglxt/xtgl/`

**Comment by NianBroken** [comment]
对于“课程推送”功能，因本项目的核心是“检查成绩更新”，与“课程推送”的项目方向不同。
所以“课程推送”将会出现在项目中，而不是本项目。
因此该issues将被关闭。
