### ISSUE TITLE
我这个是成功了吗？

### ISSUE THREAD

**Issue by GEQfa** [NianBroken/ZFCheckScores#8]
<img width="1259" alt="屏幕截图 2024-03-10 171304" src="https://github.com/NianBroken/ZFCheckScores/assets/160826802/30811b14-1ad0-4667-bf95-4bd91957385f">

**Comment by NianBroken** [comment]
把这个展开看看运行结果是什么
![image](https://github.com/NianBroken/ZFCheckScores/assets/57057288/f8fd9bdb-7ce5-4a30-bf75-ace266d624f5)

**Comment by GEQfa** [comment]
<img width="1261" alt="ScreenShot00015" src="https://github.com/NianBroken/ZFCheckScores/assets/160826802/be0255f3-6bc2-49a3-91af-47ad3cc1ba9f">

**Comment by NianBroken** [comment]
没成功
![image](https://github.com/NianBroken/ZFCheckScores/assets/57057288/e059a6c7-b6a8-4c77-9c10-42ebbb49aff2)

**Comment by GEQfa** [comment]
不知道在哪看

**Comment by GEQfa** [comment]
<img width="1259" alt="屏幕截图 2024-03-10 193650" src="https://github.com/NianBroken/ZFCheckScores/assets/160826802/6509e511-e227-4337-b8d9-44ecfbf94bf2">

**Comment by NianBroken** [comment]
我这边看你的运行结果是没有成功的
![image](https://github.com/NianBroken/ZFCheckScores/assets/57057288/b388571a-5373-45e4-bc9c-e53291945341)

**Comment by GEQfa** [comment]
今天收到了好多错误信息

**Comment by GEQfa** [comment]
<img width="1257" alt="屏幕截图 2024-03-11 121946" src="https://github.com/NianBroken/ZFCheckScores/assets/160826802/98a9e2b2-1cdf-407f-b327-3a7de3f591aa">
请问这个是什么问题

**Comment by NianBroken** [comment]
我昨晚对代码进行了优化，你同步一下上游分支就可以解决这个错误了。

**Comment by GEQfa** [comment]
好的，现在能正常运行

**Comment by GEQfa** [comment]
但不确定能不能用
