### ISSUE TITLE
请问出现这个怎么解决 TypeError: '<' not supported between instances of 'NoneType' and 'str'

### ISSUE THREAD

**Issue by SPHINX000** [NianBroken/ZFCheckScores#9]
刚重新fork的项目，按照步骤进行出现这个
![{A7D03AE2-3F55-4e18-9CAE-686B5E6F5311}](https://github.com/NianBroken/ZFCheckScores/assets/108564265/148db30d-14f3-4151-a5a5-32af3b772d2c)
教务系统URL为 https://jwglxt.haut.edu.cn/jwglxt/cjcx

**Comment by NianBroken** [comment]
这个需要你提供账号密码我才能定位问题。
可以将账号密码发送到：suinian666@gmail.com

**Comment by NianBroken** [comment]
该Bug是由于在对成绩进行排序时出现了值为`None`的`submission_time`，无法排序，而导致运行异常。
因为程序会先获取所有成绩信息，然后按照成绩提交时间`submission_time`进行排序。
最终只取前8条成绩进行推送。
现已对代码进行优化，对于值为None的submission_time，将被视为1970-01-01 00:00:00。
